server:
  port: 80
spring:
  mvc:
    static-path-pattern: /res/**
    contentnegotiation:
      favor-parameter: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: wsq20010902
      url: jdbc:mysql://101.43.249.71:3306/SY-PerceptionHole
  redis:
    password: REDIS_PASSWORD_wsq20010902
    cluster:
      nodes: 81.70.47.134:7001,81.70.47.134:7002,81.70.47.134:7003,81.70.47.134:7004,81.70.47.134:7005,81.70.47.134:7006
    client-type: jedis
    jedis:
      pool:
        enabled: true
        max-active: 100
  cache:
    type: redis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: "th_"
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root : error
my-redis-cache-config:
  enable: true
